Revert "Stop using compression for git cache update bootstrap."
This reverts commit 749139969f34788a65dc1e5e27484325035129ce.

Reason for revert: check for existence is wrong:
Failed to check GS:
CommandException: One or more URLs matched no objects.
See more https://logs.chromium.org/logs/infra-internal/buildbucket/cr-buildbucket.appspot.com/8915157478918019280/+/steps/Updating_https:__chromium.googlesource.com_android_apks/0/stdout

Original change's description:
> Stop using compression for git cache update bootstrap.
> 
> Change git cache to stop zipping the git directory and instead upload directly to GS.
> 
> Bug: 943696
> Change-Id: I310fb48ff3d7fd6781914e14e0e17530d5d9b328
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1585029
> Commit-Queue: Karen Qian <karenqian@google.com>
> Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>

TBR=tandrii@chromium.org,karenqian@google.com

Change-Id: I4c57cd6b2defdb2cf842eb0acb9c1b1cd7a96298
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 943696
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1585445
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>
Commit-Queue: Andrii Shyshkalov <tandrii@chromium.org>