Revert of Use tracking remote name for gerrit upload. (patchset #1 id:1 of https://codereview.chromium.org/1830313002/ )
Reason for revert:
Argh, this has broken uploading track-ed branches.
Repro:

git new-branch base-feature
touch x1 && git add x1 && git commit -m "x1"
git cl upload
git new-branch --upstream_current dep-feature
touch y1 && git add y1 && git commit -m "y1"
git cl upload -v -v # fails.


the verbose output produces this:
---cut---
DEBUG:root:git push . 7079b1682431184375b62e7e81ce10a02171aa0d:refs/for/refs/heads/master
To .
 ! [rejected]        7079b1682431184375b62e7e81ce10a02171aa0d -> refs/for/refs/heads/master (non-fast-forward)
error: failed to push some refs to '.'
---cut---

Original issue's description:
> Use tracking remote name for gerrit upload.
> 
> This patch replaces the hard-coded remote name 'origin' with the
> one obtained by git-remote.
> 
> Committed: http://src.chromium.org/viewvc/chrome?view=rev&revision=299491

TBR=iannucci@chromium.org,ukai@chromium.org,alokp@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1835923002

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/depot_tools@299509 0039d316-1c4b-4281-b951-d872f2087c98